version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
  application-server:
    image: application-server
    ports:
      - 8761:8761
  books-service:
    container_name: books-service
    image: books-service
    build:
      context: ../books-service
      dockerfile: Dockerfile
    environment:
      - eureka.client.serviceUrl.defaultZone=http://application-server:8761/eureka
    links:
      - mongodb
    depends_on:
      - application-server
      - mongodb
    ports:
      - 8081:8081
  search-application:
    container_name: search-application
    image: search-application
    build:
      context: ../search-application
      dockerfile: Dockerfile
    environment:
      - eureka.client.serviceUrl.defaultZone=http://application-server:8761/eureka
    depends_on:
      - application-server
    ports:
      - 8080:8080
