server:
  port: 8080
  servlet:
    context-path:

spring:
  application:
    name: search-application

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    instance:
      preferIpAddress: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


