server:
  port: 8081
  servlet:
    context-path:

spring:
  application:
    name: books-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      host: host.docker.internal
      port: 27017

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    instance:
      preferIpAddress: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


