FROM openjdk:11-jdk
MAINTAINER Paulo Pigassi
WORKDIR /app
COPY target/search-application-0.0.1-SNAPSHOT.jar /app/search-application-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "search-application-0.0.1-SNAPSHOT.jar"]